#!/bin/bash
#
# Script to fetch submodules for NCAR EARTH SYSTEM MODELS
#
set -e
########################
dir=$(git rev-parse --show-toplevel)
if ! test -f ${dir}/bin/git-fleximod; then
  echo "Getting checkout tools"
  git -C ${dir} clone https://github.com/jedwards4b/git-fleximod --depth 1 bin
fi
pushd ${dir} 1>/dev/null
python ./bin/git-fleximod install "$@"
popd 1>/dev/null
