name: cesm-derecho-hosted
run-name: ${{ github.actor }} is testing the project

on:
  pull_request:
    branches: [ testbranch ]
    types: [ labeled ]
    
jobs:
  setup:
    if: ${{ github.event.label.name == 'run-pr-tests' }}
    runs-on: hpc-runner
   
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Run git-fleximod
      run: |
        pwd
        module list
        ./bin/git-fleximod update

  reusable:
    needs: [setup]
    strategy:
      matrix:
#        compiler: [intel, intel-oneapi, gnu, nvhpc]
        compiler: [intel, intel-oneapi]
    env:
      CC: mpicc
      FC: mpifort
      CXX: mpicxx
      CIME_MODEL: cesm
      CIME_DRIVER: nuopc
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}   
    uses: ESCOMP/CESM/.github/workflows/reusable.yaml@${BRANCH_NAME}
    with:
      stage: ${{ matrix.compiler }}


