on:
  workflow_call:
    inputs:
      compiler:
        type: string
        required: true

jobs:
  test:
    runs-on: hpc-runner
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Run git-fleximod
      run: |
        pwd
        module list
        ./bin/git-fleximod update
    - name: Run ${{ inputs.compiler }} tests
      continue-on-error: true
      run: |
          pwd
          cd cime/scripts
          module load cmake
          qcmd -v PROJECT=P93300606 -A P93300606 -l walltime=02:00:00 -- ./create_test --xml-machine derecho\
              --xml-category github --no-run --compiler ${{ inputs.compiler }} --test-id ghtest.${{ inputs.compiler }}
    - name: check status
      run: |
          cd $SCRATCH
          ./cs.status.ghtest.${{ inputs.compiler }} --expected-fails-file $GITHUB_WORKSPACE/cime_config/testfiles/ExpectedTestFails.xml